main:
  - name: "About"
    url: "/"
    weight: 10
  - name: "Services"
    url: "/services/"
    weight: 20
  - name: "Codes"
    url: "/codes/"
    weight: 30
  - name: "Examples"
    url: "/examples/"
    weight: 40
